name: partnership
description: In progress

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:

  cloud_firestore: ^0.8.2+3

  flutter:
    sdk: flutter

  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  firebase_messaging: ^2.1.0
  firebase_database:

  cupertino_icons: ^0.1.2

  fluro: "^1.4.0"
  tuple: ^1.0.2
  connectivity: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/test.png
    - assets/img/logo_partnership.png
    - assets/img/work-office.png

fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Semibold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

