name: partnership
description: In progress

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:

  cloud_firestore: ^0.8.2+3

  flutter:
    sdk: flutter

  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  firebase_messaging: ^2.1.0
  path_provider: ^0.5.0+1
  firebase_storage:

  cupertino_icons: ^0.1.2

  fluro: "^1.4.0"
  tuple: ^1.0.2
  connectivity: ^0.3.2
  image_picker: ^0.4.12+1
  flushbar: ^1.3.0
  permission: ^0.1.1

  material_search: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/texts/terms&conditions.txt
    - assets/test.png
    - assets/img/logo_partnership.png
    - assets/img/work-office.png
    - assets/img/login_logo.png
    - assets/blue_texture.jpg
    - assets/bubble_texture.jpg
    - assets/

  fonts:
    - family: PeaceSans
      fonts:
        - asset: assets/PeaceSans/Peace_Sans_Webfont.ttf

    - family: Copperhead
      fonts:
        - asset: assets/fonts/Copperhead_Condensed_Demo.ttf
          style: normal

